# Generated by Django 3.1.5 on 2021-01-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=9, verbose_name='цена')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(db_index=True, verbose_name='дата начала')),
                ('date_end', models.DateField(db_index=True, verbose_name='дата окончания брони')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel.room', verbose_name='номер')),
            ],
        ),
    ]
